Repository kubernetes-sigs/kpng, pull requests merged in 2021-05, with the labels that each got.

#16 use calico cni as the kpng hack/ cni to make cluster realistic
  hack/kind.yaml
  hack/kpng-local-up.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#19 Update kpng-deployment-ds.yaml.tmpl
  hack/kpng-deployment-ds.yaml.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#23 kpng-local-up: use main instead of master
  hack/kpng-local-up.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#25 Move ipvs impl to main repo
  backends/ipvs/flags.go
  backends/ipvs/ipvs.go
  backends/ipvs/prerun.go
  cmd/kpng-ipvs-backend/kpng-ipvs-backend.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 Kpng local ipvs
  hack/README.md
  hack/kpng-deployment-ds.yaml.tmpl
  hack/kpng-local-up.sh
Labels: cncf-cla: yes, size/M

#28 Added code in NFT backend to check for iptable version
  backends/nft/nft.go
  hack/kpng-deployment-ds.yaml.tmpl
Labels: cncf-cla: yes, size/S

#29 Fix headless and service proxy name tc's
  jobs/kube2store/kube2store.go
Labels: cncf-cla: yes, size/M
