Repository kubernetes-sigs/kpng, pull requests merged in 2021-12, with the labels that each got.

#126 Adding Loadbalancer service code
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/helpers.go
  backends/ipvs-as-sink/ipset.go
  backends/ipvs-as-sink/ipvs.go
  backends/ipvs-as-sink/ipvslb.go
  backends/ipvs-as-sink/loadbalancersvc.go
  backends/ipvs-as-sink/nodeportsvc.go
  backends/ipvs-as-sink/util/ipset.go
  backends/ipvs-as-sink/util/types.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#138 remove sonobuoy GH
  .github/workflows/test_sonobuoy.yml
Labels: cncf-cla: yes, approved, lgtm, size/M

#139 add owners and approvers for ci
  .github/OWNERS
  hack/OWNERS
Labels: cncf-cla: yes, approved, size/S, lgtm

#135 porting iptable changes from kube-proxy
  backends/iptables/iptables.go
  backends/iptables/util/iptables_save_restore.go
  backends/iptables/util/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#147 fixed kubeconfig issue
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#148 fix kubeconfig 2
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#152 iptable backend changes for better readability and session affinity support
  backends/iptables/iptables.go
  backends/iptables/service.go
  backends/iptables/types.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#144 adding new OWNERS file for backend review process
  backends/OWNERS
Labels: cncf-cla: yes, approved, size/S, lgtm

#160 test_e2e: validate if docker cmd failed
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#161 test_e2e: Add container engine validation
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#163 e2e: improvements
  hack/kpng-deployment-ds.yaml.tmpl
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, size/XL, lgtm, ok-to-test

#169 test_e2e: create -d for development mode
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#168 proxystore_test: Add unit test to SessionAffinity
  server/pkg/proxystore/proxystore_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M
