Repository kubernetes-sigs/kpng, pull requests merged in 2021-11, with the labels that each got.

#87 Update all the links + agenda + goals
  README.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#79 programming only Local Endpoint in KUBE-LOOP_BACK
  Dockerfile
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/lb.go
  backends/ipvs-as-sink/nodeportsvc.go
  backends/ipvs/flags.go
  backends/ipvs/go.mod
  backends/ipvs/go.sum
  backends/ipvs/ipvs.go
  backends/ipvs/prerun.go
  backends/ipvs/util/ipset.go
  backends/ipvs/util/types.go
  client/localsink/decoder/decoder.go
  examples/pipe-exec/cmd/kpng-callout/main.go
  examples/pipe-exec/cmd/kpng-json/main.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#89 deleting remaining files of old ipvs files
  backends/ipvs/register.go
Labels: cncf-cla: yes, size/M

#90 Fix iptables backend in kpng-local-up
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/iptables/iptables.go
  backends/iptables/register.go
  backends/iptables/sink.go
  backends/nft/go.sum
  client/go.sum
  cmd/go.mod
  cmd/go.sum
  cmd/kpng/storecmds/storecmds_linux.go
  examples/iptables-extip/go.sum
  examples/pipe-exec/go.sum
  examples/print-state/go.sum
  hack/kpng-local-up.sh
  server/go.mod
  server/go.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm

#97 github actions for backend builds
  .github/workflows/backend-build.yml
  hack/build.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#98 0.17.3 for CI
  .github/workflows/backend-build.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#99 adding test_unit.sh to run all unit tests
  hack/resolve_all_mod_files.sh
  hack/test_unit.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#101 add GH actions for unit tests build
  .github/workflows/build_test_unit.yml
Labels: cncf-cla: yes, approved, lgtm, size/M

#100 more generic build.sh
  hack/build.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#106 test sonobuoy GH action
  .github/workflows/test_sonobuoy.yml
  hack/setup_sonobuoy.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#115 Fixing service event handling
  client/serviceevents/service-events.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#116 Removing not existent cni_config function
  hack/kpng-local-up.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#125 LoadBalancer support
  backends/iptables/service.go
Labels: cncf-cla: yes, approved, lgtm, size/M
