Repository kubernetes-sigs/kpng, pull requests merged in 2022-02, with the labels that each got.

#245 e2e_test: Made kind ipv6 core dns patch default when using IPv6
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#248 Fixing compilation issue
  client/serviceevents/service-events.go
  client/serviceevents/service-events_test.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#250 test_e2e: fix to make ipv6 tests run correctly (or detect incompatible sysctl settings)
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#254 conntrack: cleanup on add
  api/localnetv1/endpoint.go
  api/localnetv1/endpoint_test.go
  api/localnetv1/port-mapping.go
  api/localnetv1/service_test.go
  api/localnetv1/services.pb.go
  api/localnetv1/services.proto
  api/localnetv1/services_grpc.pb.go
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/iptables/iptables.go
  backends/nft/dnat-rule.go
  backends/nft/endpoint.go
  backends/nft/go.mod
  backends/nft/go.sum
  backends/nft/nft.go
  backends/nft/nftable.go
  backends/nft/render-context.go
  backends/nft/render-context_test.go
  backends/nft/svc-chain.go
  backends/nft/svc-chain_test.go
  client/diffstore2/diffstore.go
  client/plugins/conntrack/conntrack.go
  client/plugins/conntrack/conntrack_linux.go
  client/plugins/conntrack/flow.go
  client/plugins/conntrack/ip-port.go
  server/go.mod
  server/go.sum
  server/jobs/kube2store/slice-event-handler.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#265 server: fix hash stability issues with maps
  server/cmd/kpng-backend-torture/main.go
  server/go.mod
  server/go.sum
  server/jobs/file2store/file2store.go
  server/jobs/store2localdiff/store2localdiff.go
  server/pkg/proxystore/proxystore.go
  server/serde/serde.go
  server/serde/serde_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
