Repository kubernetes-sigs/kpng, pull requests merged in 2022-10, with the labels that each got.

#360 Fix hack README.md run from source
  hack/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#350 fix userspace panic while syncing headless svc and dns resolution
  backends/userspacelin/sink.go
  backends/userspacelin/userspace_util.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#361 Fix to run kpng-local-up.sh from source root
  hack/kpng-local-up.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#357 fix #353: remove legacy endpoints support
  server/jobs/kube2store/endpoints-event-handler.go
  server/jobs/kube2store/kube2store.go
  server/jobs/kube2store/node-event-handler.go
Labels: cncf-cla: yes, size/L, do-not-merge/invalid-commit-message, approved, lgtm

#346 Add info about allocateNodePorts=false to the service-proxy docs
  doc/service-proxy.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#363 server: move proxystore up one level
  cmd/kpng/a2s.go
  cmd/kpng/f2s.go
  cmd/kpng/k2s.go
  cmd/kpng/storecmds/storecmds.go
  server/jobs/api2localdiff/api2localdiff.go
  server/jobs/api2store/api2store.go
  server/jobs/file2store/file2store.go
  server/jobs/kube2store/event-handlers.go
  server/jobs/kube2store/kube2store.go
  server/jobs/kube2store/node-event-handler.go
  server/jobs/kube2store/service-event-handler.go
  server/jobs/kube2store/service-event-handler_test.go
  server/jobs/kube2store/slice-event-handler.go
  server/jobs/store2api/store2api.go
  server/jobs/store2diff/store2diff.go
  server/jobs/store2file/store2file.go
  server/jobs/store2globaldiff/store2globaldiff.go
  server/jobs/store2localdiff/store2localdiff.go
  server/pkg/endpoints/node.go
  server/pkg/endpoints/node_test.go
  server/pkg/proxy/server.go
  server/pkg/server/endpoints/endpoints.go
  server/pkg/server/endpoints/server.go
  server/pkg/server/global/global.go
  server/pkg/server/global/server.go
  server/proxystore/kv.go
  server/proxystore/proxystore.go
  server/proxystore/proxystore_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#364 server: add some doc with pointers to each function of the server
  server/doc.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#369 standard dev env & protoc generation
  Dockerfile
  Dockerfile.static
  api/localnetv1/services.pb.go
  api/localnetv1/services_grpc.pb.go
  backends/ebpf/go.mod
  backends/ebpf/go.sum
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/ipvs-as-sink/go.mod
  backends/ipvs-as-sink/go.sum
  backends/nft/go.mod
  backends/nft/go.sum
  backends/userspacelin/go.mod
  backends/userspacelin/go.sum
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  hack/README.md
  hack/dev-docker
  hack/docker-dev-env/Dockerfile
  hack/docker-dev-env/entrypoint.sh
  hack/protoc-gen
Labels: cncf-cla: yes, size/L, approved, lgtm

#358 Replace J2 template with Go Template
  hack/kpng-deployment-ds-template.txt
  hack/kpng-ds-yaml-gen.go
  hack/kpng-local-up.sh
  hack/test_e2e.sh
  hack/utils.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#367 update to k8s 1.25
  api/go.mod
  api/go.sum
  backends/ebpf/go.mod
  backends/ebpf/go.sum
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/ipvs-as-sink/go.mod
  backends/ipvs-as-sink/go.sum
  backends/nft/go.mod
  backends/nft/go.sum
  backends/userspacelin/go.mod
  backends/userspacelin/go.sum
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  backends/windows/userspace/go.mod
  backends/windows/userspace/go.sum
  client/go.mod
  client/go.sum
  cmd/go.mod
  cmd/go.sum
  examples/iptables-extip/go.mod
  examples/iptables-extip/go.sum
  examples/userspace-proxier/go.mod
  examples/userspace-proxier/go.sum
  from-k8s/go.mod
  from-k8s/go.sum
  go.work
  go.work.sum
  server/go.mod
  server/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#371 add userspace to ci
  .github/workflows/backend-build.yml
  .github/workflows/e2e_tests.yaml
  hack/test_backend_build.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#373 add aryan9600 to backends/OWNERS
  backends/OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#382 bump go version in CI to 1.19
  .github/workflows/backend-build.yml
  .github/workflows/e2e_tests.yaml
  .github/workflows/unit_tests.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#381 doc/arch: 2nd try at drawing :-)
  doc/arch-try-2.dia
  doc/arch-try-2.png
  doc/arch-try-2.svg
Labels: cncf-cla: yes, size/L, approved, lgtm

#368 Add rajas to OWNERS
  OWNERS
  backends/OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#370 Add Metrics + Metrics server
  cmd/kpng/main.go
  doc/grafana-kpng.png
  doc/metrics.md
  doc/prometheus-kpng.png
  go.work.sum
  hack/kpng-deployment-ds-template.txt
  hack/kpng-ds-yaml-gen.go
  hack/kpng-service-monitor.yaml
  hack/prometheus.yml
  hack/test_e2e.sh
  hack/utils.sh
  server/go.mod
  server/go.sum
  server/jobs/api2local/api2local.go
  server/jobs/kube2store/kube2store.go
  server/pkg/metrics/metrics.go
  server/pkg/server/watchstate/watchstate.go
  server/proxystore/proxystore.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#284 Added unit test of iptables
  backends/ipvs-as-sink/go.mod
  backends/ipvs-as-sink/go.sum
  backends/ipvs-as-sink/iptables_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
