Repository kubernetes-sigs/kpng, pull requests merged in 2022-01, with the labels that each got.

#175 go.sum files for ipvs backend
  backends/ipvs-as-sink/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#173 e2e_export_logs: remove warning message
  hack/e2e_export_logs.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#176 ipvs: validate net.ParseCIDR
  backends/ipvs-as-sink/ipvs.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#166 ipvs iptable implementation
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/flags.go
  backends/ipvs-as-sink/helpers.go
  backends/ipvs-as-sink/ipset.go
  backends/ipvs-as-sink/iptables.go
  backends/ipvs-as-sink/ipvs.go
  backends/ipvs-as-sink/loadbalancersvc.go
  backends/ipvs-as-sink/nodeportsvc.go
  backends/ipvs-as-sink/proxier.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#180 FIx small typo in readme.md
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#171 Using golang protobuf library
  cmd/go.mod
  cmd/go.sum
  server/pkg/proxystore/proxystore.go
  server/pkg/proxystore/proxystore_test.go
  server/pkg/server/watchstate/watchstate.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#183 kpng-local-up: add missing env vars
  hack/kpng-local-up.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#184 README: add APAC meeting details
  README.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#172 build: Add initial Makefile
  Makefile
Labels: cncf-cla: yes, size/L, approved, lgtm

#177 ipset: avoid dup code for diffstrings
  api/localnetv1/ipset.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#186 Default value for masqueradeAll flag for iptables
  backends/iptables/iptables.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#192 iptables: use the type EndpointsMap
  backends/iptables/endpoints.go
  backends/iptables/endpointsCache.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#185 Make hack/test_e2e assume less about environment around it
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/L, approved, lgtm

#190 externalIP implementation for cluster ip service
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/externalIP.go
  backends/ipvs-as-sink/helpers.go
  backends/ipvs-as-sink/iptables.go
  backends/ipvs-as-sink/ipvs.go
  backends/ipvs-as-sink/loadbalancersvc.go
  backends/ipvs-as-sink/nodeportsvc.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#193 hack: add dougsland to OWNERS
  hack/OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm, ok-to-test

#188 hack: README - add steps for single E2E test
  hack/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#195 hack: few adjusts for README.md
  hack/README.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#208 More documentation about development
  hack/README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#207 backend/iptables: rename vars
  backends/iptables/endpoints.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#167 go-mod-tidy-all: add validations
  go-mod-tidy-all
Labels: cncf-cla: yes, approved, lgtm, size/M

#213 fail kpng local up if compilation is broken
  hack/kpng-local-up.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#189 Fixing DeleteIPPort API with currentSvc object
  client/serviceevents/service-events.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#226 internal traffic policy changes in kpng server
  api/localnetv1/services.pb.go
  api/localnetv1/services.proto
  server/jobs/kube2store/service-event-handler.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#209 Add contributing w/ notes on minutia
  CONTRIBUTING.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#205 adding session affinity code in ipvs
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/externalIP.go
  backends/ipvs-as-sink/ipvslb.go
  backends/ipvs-as-sink/loadbalancersvc.go
  backends/ipvs-as-sink/nodeportsvc.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#83 kpng winuserspace backend
  backends/windows/OWNERS
  backends/windows/userspace/README.md
  backends/windows/userspace/backend.go
  backends/windows/userspace/go.mod
  backends/windows/userspace/go.sum
  backends/windows/userspace/loadbalancer.go
  backends/windows/userspace/main.go
  backends/windows/userspace/proxier.go
  backends/windows/userspace/proxysocket.go
  backends/windows/userspace/roundrobin.go
  backends/windows/userspace/roundrobin_test.go
  backends/windows/userspace/service.go
  backends/windows/userspace/types.go
  backends/windows/userspace/utils.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#229 Fix external ip panic on no endpoints
  backends/iptables/iptables.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#230 fix for kpng server crash
  server/jobs/kube2store/service-event-handler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#231 adding myself, vivek root owners
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#232 Fixing targetport and adding klog flags
  backends/windows/userspace/backend.go
  backends/windows/userspace/loadbalancer.go
  backends/windows/userspace/main.go
  backends/windows/userspace/proxier.go
  backends/windows/userspace/proxysocket.go
  backends/windows/userspace/roundrobin.go
  backends/windows/userspace/utils.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#236 Enhancing service events for traffic policy and session affinity
  backends/ipvs-as-sink/ipvs.go
  client/serviceevents/service-events.go
  client/serviceevents/service-events_test.go
  client/serviceevents/traffic_policy_kind.go
  client/serviceevents/wrap.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#239 Multiport fix when targetport is a string
  api/localnetv1/services.pb.go
  api/localnetv1/services.proto
  api/localnetv1/services_grpc.pb.go
  backends/iptables/iptables.go
  backends/iptables/service.go
  server/jobs/kube2store/slice-event-handler.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#242 EndpointPortMap update fix
  server/jobs/kube2store/slice-event-handler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#238 test_e2e can now run parallel e2e test on multiple clusters with the same -i and -b configuration
  .github/workflows/e2e_tests.yaml
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, size/XL, lgtm
