Repository kubernetes-sigs/kpng, pull requests merged in 2022-09, with the labels that each got.

#340 Remove reference to endpoint's type
  backends/windows/kernelspace/endpoints.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#338 Remove static headerfiles
  backends/ebpf/.gitignore
  backends/ebpf/Makefile
  backends/ebpf/README.md
  backends/ebpf/bpf/cgroup_connect4.c
  backends/ebpf/bpf/headers/bpf_endian.h
  backends/ebpf/bpf/headers/bpf_helper_defs.h
  backends/ebpf/bpf/headers/bpf_helpers.h
  backends/ebpf/bpf/headers/bpf_tracing.h
  backends/ebpf/bpf/headers/common.h
  backends/ebpf/bpf_bpfeb.o
  backends/ebpf/bpf_bpfel.o
  backends/ebpf/ebpf.go
  backends/ebpf/hack/install-libbpf.sh
  go.work.sum
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#343 Bumped e2e CI to k8s latest release
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#345 cleanup and repair of test_e2e.sh
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#348 Update kpng-local-up.sh and fix potential IPVS panic
  .github/workflows/backend-build.yml
  .github/workflows/e2e_tests.yaml
  .github/workflows/unit_tests.yml
  backends/ipvs-as-sink/ipvs.go
  hack/kpng-local-up.sh
  hack/test_e2e.sh
  hack/utils.sh
Labels: cncf-cla: yes, size/L, approved, lgtm
