Repository kubernetes-sigs/kpng, pull requests merged in 2022-07, with the labels that each got.

#295 Fix masquerading in NFT backend
  backends/nft/nft.go
  backends/nft/render-context_test.go
  hack/kpng-deployment-ds.yaml.tmpl
  hack/kpng-local-up.sh
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#297 Switch all usages of klog v1 to klog v2 for consistency
  .gitignore
  backends/ipvs-as-sink/clusteripsvc.go
  backends/ipvs-as-sink/common.go
  backends/ipvs-as-sink/externalIP.go
  backends/ipvs-as-sink/go.mod
  backends/ipvs-as-sink/go.sum
  backends/ipvs-as-sink/ipset.go
  backends/ipvs-as-sink/iptables.go
  backends/ipvs-as-sink/ipvs.go
  backends/ipvs-as-sink/loadbalancersvc.go
  backends/ipvs-as-sink/nodeportsvc.go
  backends/ipvs-as-sink/util/ipset.go
  backends/ipvs-as-sink/util/iptables.go
  backends/ipvs-as-sink/util/utils.go
  backends/nft/dnat-rule.go
  backends/nft/go.mod
  backends/nft/go.sum
  backends/nft/nft.go
  backends/nft/system-checks.go
  client/run.go
  cmd/go.mod
  cmd/go.sum
  cmd/kpng-globallog/main.go
  cmd/kpng-nodelog/main.go
  cmd/kpng/main.go
  go.work.sum
  server/cmd/kpng-backend-torture/main.go
  server/go.mod
  server/go.sum
  server/jobs/api2store/api2store.go
  server/jobs/file2store/file2store.go
  server/jobs/kube2store/kube2store.go
  server/jobs/kube2store/service-event-handler.go
  server/jobs/kube2store/slice-event-handler.go
  server/jobs/store2file/store2file.go
  server/pkg/proxy/server.go
  server/pkg/proxystore/proxystore.go
  server/pkg/server/endpoints/server.go
  server/pkg/server/server.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#304 Remove duplicate function in e2e-test.sh
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#309 Add ebpf backend to CI
  .github/workflows/e2e_tests.yaml
  backends/ebpf/ebpf.go
  backends/ebpf/register.go
  backends/ebpf/types.go
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#306 Include example in go.work
  go.work
  hack/go-build
Labels: cncf-cla: yes, size/XS, approved, lgtm
