Repository kubernetes-sigs/kpng, pull requests merged in 2022-08, with the labels that each got.

#320 watchstate: allow multiple stores per set
  server/pkg/server/watchstate/watchstate.go
Labels: cncf-cla: yes, approved, size/S

#319 test e2e: improve IPv6 handling and bump versions
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/M

#314 Change endpoint key and use anonymous set depending on presence of PodName
  api/localnetv1/services.pb.go
  api/localnetv1/services.proto
  api/localnetv1/services_grpc.pb.go
  client/serviceevents/service-events.go
  server/jobs/kube2store/endpoints-event-handler.go
  server/jobs/kube2store/slice-event-handler.go
  server/jobs/store2localdiff/store2localdiff.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#217 Windows kernelspace!!!
  .gitignore
  Makefile
  backends/windows/kernelspace/OWNERS
  backends/windows/kernelspace/README.md
  backends/windows/kernelspace/build.sh
  backends/windows/kernelspace/config.go
  backends/windows/kernelspace/cross-compile.sh
  backends/windows/kernelspace/dualstack.go
  backends/windows/kernelspace/endpoints.go
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  backends/windows/kernelspace/hcnutils.go
  backends/windows/kernelspace/metrics.go
  backends/windows/kernelspace/proxier.go
  backends/windows/kernelspace/proxier_events.go
  backends/windows/kernelspace/service.go
  backends/windows/kernelspace/sink.go
  backends/windows/kernelspace/types.go
  backends/windows/kernelspace/util.go
  cmd/kpng/storecmds/storecmds_windows.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#316 bump go to 1.19
  .dockerignore
  Dockerfile
  Dockerfile.static
  api/go.mod
  api/go.sum
  backends/ebpf/go.mod
  backends/ebpf/go.sum
  backends/windows/userspace/go.mod
  backends/windows/userspace/go.sum
  examples/iptables-extip/go.mod
  examples/iptables-extip/go.sum
  examples/pipe-exec/go.mod
  examples/pipe-exec/go.sum
  examples/print-state/go.mod
  examples/print-state/go.sum
  examples/userspace-proxier/go.mod
  examples/userspace-proxier/go.sum
Labels: cncf-cla: yes, size/XXL, approved

#318 migrate to discovery/v1
  api/localnetv1/services.pb.go
  api/localnetv1/services.proto
  api/localnetv1/services_grpc.pb.go
  backends/iptables/endpoints.go
  server/jobs/kube2store/endpoints-event-handler.go
  server/jobs/kube2store/kube2store.go
  server/jobs/kube2store/node-event-handler.go
  server/jobs/kube2store/service-event-handler_test.go
  server/jobs/kube2store/slice-event-handler.go
  server/pkg/endpoints/node.go
  server/pkg/endpoints/node_test.go
Labels: cncf-cla: yes, approved, size/XL

#331 fix godeps
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  client/go.mod
  client/go.sum
  cmd/go.mod
  cmd/go.sum
  go.work.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#334 Add gcc-multilib as dependency
  backends/ebpf/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#333 cleanup the build for winkernel
  api/go.mod
  api/go.sum
  backends/ebpf/go.mod
  backends/ebpf/go.sum
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/ipvs-as-sink/go.mod
  backends/ipvs-as-sink/go.sum
  backends/nft/go.mod
  backends/nft/go.sum
  backends/userspacelin/go.mod
  backends/userspacelin/go.sum
  backends/windows/kernelspace/.gitignore
  backends/windows/kernelspace/cross-compile.sh
  backends/windows/kernelspace/dualstack.go
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  backends/windows/kernelspace/proxier.go
  backends/windows/kernelspace/sink.go
  backends/windows/userspace/go.mod
  backends/windows/userspace/go.sum
  client/go.mod
  client/go.sum
  cmd/go.mod
  cmd/go.sum
  examples/iptables-extip/go.mod
  examples/iptables-extip/go.sum
  examples/pipe-exec/go.mod
  examples/print-state/go.mod
  examples/userspace-proxier/go.mod
  examples/userspace-proxier/go.sum
  from-k8s/README.md
  from-k8s/go.mod
  from-k8s/go.sum
  from-k8s/pkg/apis/core/annotation_key_constants.go
  from-k8s/pkg/apis/core/doc.go
  from-k8s/pkg/apis/core/helper/helpers.go
  from-k8s/pkg/apis/core/json.go
  from-k8s/pkg/apis/core/objectreference.go
  from-k8s/pkg/apis/core/register.go
  from-k8s/pkg/apis/core/resource.go
  from-k8s/pkg/apis/core/taint.go
  from-k8s/pkg/apis/core/toleration.go
  from-k8s/pkg/apis/core/types.go
  from-k8s/pkg/apis/core/v1/helper/helpers.go
  from-k8s/pkg/apis/core/v1/helper/qos/qos.go
  from-k8s/pkg/apis/core/zz_generated.deepcopy.go
  from-k8s/pkg/features/kube_features.go
  from-k8s/pkg/proxy/util/endpoints.go
  from-k8s/pkg/proxy/util/network.go
  from-k8s/pkg/proxy/util/testing/fake.go
  from-k8s/pkg/proxy/util/utils.go
  from-k8s/pkg/util/async/bounded_frequency_runner.go
  from-k8s/pkg/util/async/runner.go
  go.work
  go.work.sum
  server/go.mod
  server/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#341 Expose winkernel settings as flags instead of hard-coded values...
  backends/windows/kernelspace/proxier.go
  backends/windows/kernelspace/sink.go
Labels: cncf-cla: yes, size/L, approved, lgtm
