Repository kubernetes-sigs/kpng, pull requests merged in 2023-01, with the labels that each got.

#426 Moving command_builder to builder module
  cmd/kpng/a2s.go
  cmd/kpng/builder/command_builder.go
  cmd/kpng/f2s.go
  cmd/kpng/k2s.go
  cmd/kpng/local.go
  cmd/kpng/main.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#429 chore: remove buffers on some chans
  client/client.go
  client/localsink/fullstate/fullstate.go
  client/localsink/fullstate/fullstatepipe/fullstatepipe.go
  server/pkg/proxy/server.go
Labels: cncf-cla: yes, size/XS, approved

#431 add security pipeline that scans with gosec and govulncheck
  .github/workflows/security.yaml
Labels: cncf-cla: yes, approved, lgtm, ok-to-test, size/M

#432 Add dependency review enforcement action
  .github/workflows/security.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#417 IPVS Fullstate Implementation
  backends/ipvsfullstate/README.md
  backends/ipvsfullstate/common.go
  backends/ipvsfullstate/controller.go
  backends/ipvsfullstate/flags.go
  backends/ipvsfullstate/go.mod
  backends/ipvsfullstate/go.sum
  backends/ipvsfullstate/handle_clusterip_service.go
  backends/ipvsfullstate/handle_loadbalancer_service.go
  backends/ipvsfullstate/handle_nodeport_service.go
  backends/ipvsfullstate/internal/ipsets/entry.go
  backends/ipvsfullstate/internal/ipsets/ipset.go
  backends/ipvsfullstate/internal/ipsets/ipset_util.go
  backends/ipvsfullstate/internal/ipsets/manager.go
  backends/ipvsfullstate/internal/ipsets/runner.go
  backends/ipvsfullstate/internal/ipsets/setup.go
  backends/ipvsfullstate/internal/ipsets/types.go
  backends/ipvsfullstate/internal/iptables/manager.go
  backends/ipvsfullstate/internal/iptables/templates.go
  backends/ipvsfullstate/internal/iptables/types.go
  backends/ipvsfullstate/internal/ipvs/destination.go
  backends/ipvsfullstate/internal/ipvs/manager.go
  backends/ipvsfullstate/internal/ipvs/server.go
  backends/ipvsfullstate/internal/ipvs/setup.go
  backends/ipvsfullstate/internal/ipvs/types.go
  backends/ipvsfullstate/internal/ipvs/util.go
  backends/ipvsfullstate/ipset_definitions.go
  backends/ipvsfullstate/ipset_entry_builder.go
  backends/ipvsfullstate/iptable_rules.go
  backends/ipvsfullstate/register.go
  backends/ipvsfullstate/setup.go
  backends/ipvsfullstate/types.go
  cmd/kpng/storecmds/storecmds_linux.go
  go.work
  hack/test_backend_build.sh
  hack/test_e2e.sh
  hack/tilt/deploy.sh
  hack/tilt/setup.sh
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#435 Ignore gosec false positives
  .github/workflows/security.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#437 Added skip filters to make it possible for ci/cd test succeed
  .github/workflows/e2e_tests.yaml
  hack/test_e2e.sh
  hack/test_skip_list.sh
  hack/utils.sh
Labels: cncf-cla: yes, size/L, approved, lgtm
