Repository kubernetes-sigs/kpng, pull requests merged in 2023-08, with the labels that each got.

#522 Remove ipvsadm step
  .github/workflows/e2e_tests.yaml
  backends/ipvs/internal/ipvs/setup.go
  backends/ipvs/internal/ipvs/util.go
  backends/ipvs/setup.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#523 Fix artifacts directory path.
  .github/workflows/e2e_tests.yaml
  hack/test_e2e.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#525 Downgrade kpng alpine image to align nftables with nodes OS.
  Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#427 fix kpng version command and standardize build command
  Dockerfile
  Makefile
  cmd/kpng/main.go
  cmd/kpng/version.go
  hack/common.sh
  hack/go-build
  hack/kpng-local-up.sh
  hack/test_e2e.sh
  hack/tilt/deploy.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#526 docker: upgrade to golang 1.21 and alpine 3.18
  .github/workflows/backend-build.yml
  .github/workflows/unit_tests.yml
  .github/workflows/vet-code.yml
  Dockerfile
  Dockerfile.static
  api/go.mod
  api/go.sum
  backends/ebpf/go.mod
  backends/ebpf/go.sum
  backends/healthchecks/go.mod
  backends/healthchecks/go.sum
  backends/iptables/go.mod
  backends/iptables/go.sum
  backends/ipvs/go.mod
  backends/ipvs/go.sum
  backends/nft/go.mod
  backends/nft/go.sum
  backends/userspacelin/go.mod
  backends/userspacelin/go.sum
  backends/windows/kernelspace/go.mod
  backends/windows/kernelspace/go.sum
  backends/windows/userspace/go.mod
  backends/windows/userspace/go.sum
  client/go.mod
  client/go.sum
  cmd/go.mod
  cmd/go.sum
  examples/iptables-extip/go.mod
  examples/iptables-extip/go.sum
  from-k8s/go.mod
  from-k8s/go.sum
  go.work
  go.work.sum
  hack/docker-dev-env/Dockerfile
  hack/test_e2e.sh
  server/go.mod
  server/go.sum
Labels: cncf-cla: yes, approved, size/XL, lgtm
