Repository kubernetes-sigs/kpng, pull requests merged in 2023-05, with the labels that each got.

#507 IPVS CI fix for k/k v1.26.0+
  .github/workflows/e2e_tests.yaml
  hack/test_skip_list.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#505 rename EndpointsClient to LocalClient
  client/client.go
  client/localsink/fullstate/fullstate.go
  client/run.go
  cmd/kpng-globallog/main.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#512 Add SHA to image tag
  hack/test_e2e.sh
Labels: cncf-cla: yes, approved, lgtm, ok-to-test, size/M

#506 Add gcc-multilib as eBPF pre-requisite for Ubuntu
  backends/ebpf/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#513 ipv4-ipvs: enable passing tests
  hack/test_skip_list.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#516 apt-get update before installing ebpf's backend dependencies
  .github/workflows/e2e_tests.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#515 github user-name changed
  OWNERS
Labels: cncf-cla: yes, size/XS, approved
